sudo: required
services: 
        - docker

before_install:
        - docker build -t vikas/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vikas/react-test npm test 

after_success:
        - docker build -t vikgoel1992/multi-client ./client
        - docker build -t vikgoel1992/multi-nginx ./nginx
        - docker build -t vikgoel1992/multi-server ./server
        - docker build -t vikgoel1992/multi-worker ./worker
        - echo "$Docker_Password" | docker login -u "$Docker_Id" --password-stdin       
        - docker push vikgoel1992/multi-client
        - docker push vikgoel1992/multi-nginx
        - docker push vikgoel1992/multi-server
        - docker push vikgoel1992/multi-worker

deploy:
        provider: elasticbeanstalk
        region: us-east-1
        app: multi-docker
        env: MultiDocker-env-1
        bucket_name: elasticbeanstalk-us-east-1-099878648584
        bucket_path: docker_multi
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY




