sudo: required
services: 
        - docker

before_install:
        - docker build -t vikas/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vikas/react-test npm test 

after_success:
        - docker build -t vikas/multi-client ./client
        - docker build -t vikas/multi-nginx ./nginx
        - docker build -t vikas/multi-server ./server
        - docker build -t vikas/multi-worker ./worker
        - echo "$Docker_Password" | docker login -u "$Docker_Id" --password-stdin       
        - docker push vikas/multi-client
        - docker push vikas/multi-nginx
        - docker push vikas/multi-server
        - docker push vikas/multi-worker



